# Generated by Django 3.0.2 on 2020-01-21 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
