# Generated by Django 3.0.2 on 2020-01-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myApi', '0002_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='(000)000-0000', max_length=30, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, help_text='example@email.com', max_length=128, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
            },
        ),
    ]
